spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ducks
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ducks

  sql:
    init:
      mode: always